### ISSUE TITLE
Error when updating to 1.4 of Starter-Parent / Updating spring cloud dep to brixton

### ISSUE THREAD

**Issue by sialcasa** [spring-guides/gs-service-registration-and-discovery#1]
I'm new to spring and I'm currently trying the Netflix stack. I noticed that a new version of boot released, so I tried to update to the new dependency.

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.0.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
</parent>
```

I get

```

Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationListener : org.springframework.boot.logging.ClasspathLoggingApplicationListener
    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:422)
    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:401)
    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:392)
    at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:263)
    at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
    at hello.EurekaServiceApplication.main(EurekaServiceApplication.java:12)
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/event/GenericApplicationListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:414)
    ... 7 more
Caused by: java.lang.ClassNotFoundException: org.springframework.context.event.GenericApplicationListener
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 21 more
```

When I also try to update

```
<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-parent</artifactId>
                <version>Brixton.SR4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

I get 

Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/factory/ObjectProvider

**Comment by gregturn** [comment]
Several changes in various bits required a little more detailed edit. But it should work fine now.

**Comment by albertoaflores** [comment]
I'm still getting the same error. The one different thing I'm doing is loading spring-boot dependencies via DependencyManagement (as opposed to the parent pom, we already have a parent pom). Do you know if this fix is supposed to address that?

**Comment by dsyer** [comment]
You might need the spring boot BOM to listed first.

**Comment by albertoaflores** [comment]
Caught my problem! The parent pom was defining a DependencyManagement  and it was overriding the ones defined in the child pom (DependencyManagement). Not sure what to do on that case, other than biting the bullet and update the parent pom to use the recommended DependencyManagement from the latest boot import. Thoughts?

**Comment by dsyer** [comment]
No thoughts without seeing the code. I'm not really sure what you parent is doing. Anyway, upgrading to the latest stable version is usually the best bet.

**Comment by sayali10** [comment]
@albertoaflores What did you do to solve the problem? I am facing the same issue.

**Comment by marcelopcolombo** [comment]
I am facing the same issue.
